name: Build and Publish to Docker Registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.2.2

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t app:v1 .
          docker tag app:v1 mcsolkeens/app_dev
          docker push mcsolkeens/app_dev
